// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlnlkWBj_rn_rRf8UodfiiuxJh2XfFldM',
    appId: '1:633365782640:web:d33781e8462d61dc7214b5',
    messagingSenderId: '633365782640',
    projectId: 'firbase-chatapp-93c5b',
    authDomain: 'firbase-chatapp-93c5b.firebaseapp.com',
    databaseURL: 'https://firbase-chatapp-93c5b-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-chatapp-93c5b.appspot.com',
    measurementId: 'G-H99WJGN63B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV3yAKxPQjU4mPxvLE8-EcCgsa3QzPFSE',
    appId: '1:633365782640:android:dcb3df67dc8dda0b7214b5',
    messagingSenderId: '633365782640',
    projectId: 'firbase-chatapp-93c5b',
    databaseURL: 'https://firbase-chatapp-93c5b-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-chatapp-93c5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL3IS3EN6QKFjnvrx2c1Ktge3EoOMojdY',
    appId: '1:633365782640:ios:ad3315e65188f0717214b5',
    messagingSenderId: '633365782640',
    projectId: 'firbase-chatapp-93c5b',
    databaseURL: 'https://firbase-chatapp-93c5b-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-chatapp-93c5b.appspot.com',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL3IS3EN6QKFjnvrx2c1Ktge3EoOMojdY',
    appId: '1:633365782640:ios:ad3315e65188f0717214b5',
    messagingSenderId: '633365782640',
    projectId: 'firbase-chatapp-93c5b',
    databaseURL: 'https://firbase-chatapp-93c5b-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-chatapp-93c5b.appspot.com',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlnlkWBj_rn_rRf8UodfiiuxJh2XfFldM',
    appId: '1:633365782640:web:00f29464c50181b57214b5',
    messagingSenderId: '633365782640',
    projectId: 'firbase-chatapp-93c5b',
    authDomain: 'firbase-chatapp-93c5b.firebaseapp.com',
    databaseURL: 'https://firbase-chatapp-93c5b-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-chatapp-93c5b.appspot.com',
    measurementId: 'G-VYXB54FRMQ',
  );

}